src/Lexik/Bundle/TopOrFlopBundle/Entity/Media.php
<?php

namespace Lexik\Bundle\TopOrFlopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Media
 *
 * @package Lexik\Bundle\TopOrFlopBundle\Entity
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Lexik\Bundle\TopOrFlopBundle\Repository\MediaRepository")
 */
class Media
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string $url
     *
     * @ORM\Column(name="url", type="string", length=255)
     *
     * @Assert\NotBlank()
     */
    private $url;

    /**
     * @var string $title
     *
     * @ORM\Column(name="title", type="string", length=255)
     *
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var float $average
     *
     * @ORM\Column(name="average", type="float", nullable=true)
     */
    private $average;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="Lexik\Bundle\TopOrFlopBundle\Entity\Vote",
     *     mappedBy="media",
     *     cascade={"persist"}
     * )
     *
     * @Serializer\Exclude()
     */
    private $votes;

    /**
     * @ORM\ManyToOne(targetEntity="Lexik\Bundle\TopOrFlopBundle\Entity\Categorie", inversedBy="medias", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->votes = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param  string $url
     * @return Media
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set title
     *
     * @param  string $title
     * @return Media
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set average
     *
     * @param float $average
     */
    public function setAverage($average)
    {
        $this->average = $average;
    }

    /**
     * Get average
     *
     * @return float
     */
    public function getAverage()
    {
        return $this->average;
    }

    /**
     * Add Vote
     *
     * @param Vote $vote
     */
    public function addVote(Vote $vote)
    {
        $vote->setMedia($this);
        $this->votes[] = $vote;

        $this->computeAverageScore();
    }

    /**
     * Get Votes
     *
     * @return ArrayCollection
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Calculate the average score of the media
     */
    public function computeAverageScore()
    {
        /**
         * @todo it's done!
         */
        $votesSum = 0;
        foreach ($this->votes as $vote){
            $votesSum += $vote->getScore();
        }
        $this->average = $votesSum/count($this->votes);
    }

    /**
     * Average score formatted for display
     *
     * @return string
     */
    public function getDisplayedAverage()
    {
        return (null === $this->average) ? '-' : sprintf('%.1f', $this->average);
    }

    /**
     * Whether the user has already voted for this media or not
     *
     * @param  User $user
     *
     * @return boolean
     */
    public function hasUserAlreadyVoted(User $user)
    {
        foreach ($this->votes as $vote) {
            if ($vote->getUser() == $user) {
                return true;
            }
        }

        return false;
    }

    /**
     * Remove votes
     *
     * @param \Lexik\Bundle\TopOrFlopBundle\Entity\Vote $votes
     */
    public function removeVote(\Lexik\Bundle\TopOrFlopBundle\Entity\Vote $votes)
    {
        $this->votes->removeElement($votes);
    }

    /**
     * Set categorie
     *
     * @param \Lexik\Bundle\TopOrFlopBundle\Entity\Categorie $categorie
     * @return Media
     */
    public function setCategorie(\Lexik\Bundle\TopOrFlopBundle\Entity\Categorie $categorie)
    {
        $this->categorie = $categorie;
    
        return $this;
    }

    /**
     * Get categorie
     *
     * @return \Lexik\Bundle\TopOrFlopBundle\Entity\Categorie 
     */
    public function getCategorie()
    {
        return $this->categorie;
    }
}

src/Lexik/Bundle/TopOrFlopBundle/Controller/BackendController.php
<?php

namespace Lexik\Bundle\TopOrFlopBundle\Controller;

use Lexik\Bundle\TopOrFlopBundle\Entity\Media;
use Lexik\Bundle\TopOrFlopBundle\Form\MediaType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * Class BackendController
 *
 * @package Lexik\Bundle\TopOrFlopBundle\Controller
 *
 * @Route("/backend")
 */
class BackendController extends Controller
{
    /**
    * @Route("/", name="backend_index")
    *
    * @return Response
    */
    public function indexAction()
    {
        return $this->render('LexikTopOrFlopBundle:Backend:index.html.twig');
    }
    
    /**
     * @Route("/list", name="backend_list")
     *
     * @return Response
     */
    public function showMediasAction()
    {
        $medias = $this->getDoctrine()
                ->getManager()
                ->getRepository('Lexik\Bundle\TopOrFlopBundle\Entity\Media')
                ->findAll();

        return $this->render('LexikTopOrFlopBundle:Backend:list.html.twig', array(
            'medias' => $medias,
        ));
    }
    
    /**
     * @Route("/new", name="backend_new")
     *
     * @param Request $request
     *
     * @return RedirectResponse|Response
     */
    public function newAction(Request $request)
    {
        $media = new Media();

        $form = $this->createForm(new MediaType(), $media);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->get('doctrine.orm.entity_manager');
            $em->persist($media);
            $em->flush();

            return $this->redirect($this->generateUrl('backend_list'));
        }

        return $this->render('LexikTopOrFlopBundle:Backend:new.html.twig', array(
            'form'  => $form->createView(),
        ));
    }
    
    /**
     * @Route("/edit/{id}", name="backend_edit")
     *
     * @param Request $request
     * @param integer $id
     *
     * @return RedirectResponse|Response
     */
    public function editAction(Request $request, $id)
    {
        $media = $this->getDoctrine()
                ->getManager()
                ->getRepository('Lexik\Bundle\TopOrFlopBundle\Entity\Media')
                ->find($id)
        ;

        if (null === $media) {
            throw new NotFoundHttpException("Le média d'id ".$id." n'existe pas.");
        }
        
        $form = $this->createForm(new MediaType(), $media);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->get('doctrine.orm.entity_manager');
            $em->persist($media);
            $em->flush();

            return $this->redirect($this->generateUrl('backend_list'));
        }

        return $this->render('LexikTopOrFlopBundle:Backend:new.html.twig', array(
            'form'  => $form->createView(),
        ));
    }
    
    /**
     * @Route("/del/{id}", name="backend_del")
     *
     * @param Request $request
     * @param integer $id
     *
     * @return RedirectResponse|Response
     */
    public function delAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $media = $em->getRepository('Lexik\Bundle\TopOrFlopBundle\Entity\Media')->find($id);

        if (null === $media) {
            throw new NotFoundHttpException("Le média d'id ".$id." n'existe pas.");
        }

        $form = $this->createFormBuilder()->getForm();

        if ($form->handleRequest($request)->isValid()) {
            $em->remove($media);
            $em->flush();

            return $this->redirect($this->generateUrl('backend_list'));
        }

        return $this->render('LexikTopOrFlopBundle:Backend:del.html.twig', array(
            'media'  => $media,
            'form'  => $form->createView(),
        ));
    }
}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Backend/del.html.twig
{% extends "LexikTopOrFlopBundle::backend_layout.html.twig" %}

{% block content %}
  <p>Etes-vous certain de vouloir supprimer le media "{{ media.title }}" ?</p>

  <form action="{{ path('backend_del', {'id': media.id}) }}" method="post">
    <a href="{{ path('backend_list') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la liste
    </a>
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {{ form_rest(form) }}
  </form>

{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Backend/edit.html.twig
{% extends "LexikTopOrFlopBundle::backend_layout.html.twig" %}

{% block content %}
    {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.url) }}
        {{ form_row(form.categorie) }}
        {{ form_widget(form.save, { 'label': 'Enregistrer' }) }}
    {{ form_end(form) }}
{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Backend/index.html.twig
{% extends "LexikTopOrFlopBundle::backend_layout.html.twig" %}

{% block title 'Top or Flop - accueil' %}

{% block content %}
    Bienvenue sur le Backend !
{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Backend/list.html.twig
{% extends "LexikTopOrFlopBundle::backend_layout.html.twig" %}

{% block content %}
    <h2>Liste des médias</h2>
    {% for index, media in medias %}
        {% include "LexikTopOrFlopBundle:Backend:media_list.html.twig" with { 'media': media } %}
        <br />
    {% endfor %}
{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Backend/media_list.html.twig
<a href="{{ path('show_media', {'id': media.id}) }}">
    {{ media.title }}
</a>
- {{ media.displayedAverage }}/10
<i>({{ media.votes | length }} votes)</i>
{% spaceless %}
    <a href="{{ path('backend_edit', {'id': media.id}) }}">
        <button type="button" class="btn btn-default btn-xs">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editer
        </button>
    </a>
    <a href="{{ path('backend_del', {'id': media.id}) }}">
        <button type="button" class="btn btn-default btn-xs">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Supprimer
        </button>
    </a>
{% endspaceless %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Backend/new.html.twig
{% extends "LexikTopOrFlopBundle::backend_layout.html.twig" %}

{% block content %}
    {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.url) }}
        {{ form_row(form.categorie) }}
        {{ form_widget(form.save, { 'label': 'Enregistrer' }) }}
    {{ form_end(form) }}
{% endblock %}